### ISSUE TITLE
Support initial UI

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/dashboard#19]
Create the Support System initial UI.

It should work as a E-mail inbox, listing the Github issues instead of emails

Table fields
- title
- last replied by
- status

Features
- Filter the table by issue status
- Order by latest/newest
- Search 
- Pagination (25 per page)

**Comment by MiroBenicio** [comment]
the final screen will be different, since primevue does not give table personalization in the UI kit. It will have filters, paginations and search

<img width="659" alt="Captura de Tela 2024-07-02 às 14 31 32" src="https://github.com/mytiki/dashboard/assets/96149507/389aecf0-2944-451e-a91a-2365aed9c5a8">
